300	0	reverse_gravity/gravity_up.asm
301	0	reverse_gravity/gravity_down.asm
302	0	reverse_gravity/gravity_up_down.asm
303	0	Decreases the coin counter unless it's already zero, in which case it substracts an 1-Up.
304	0	A vine that can be climbed on from behind.
305	0	This block changes into the next Map16 number when touched from the side while carrying a configurable sprite.
307	0	A horizontal vine tile.
308	0	Teleports the player.
400	0	SSP_Tiles/top_vertical_pipe_cap_L.asm
401	0	SSP_Tiles/top_vertical_pipe_cap_R.asm
402	0	SSP_Tiles/pass_if_in_pipe.asm
403	0	SSP_Tiles/pass_if_in_pipe.asm
404	0	SSP_Tiles/pass_if_in_pipe.asm
405	0	SSP_Tiles/pass_if_in_pipe.asm
406	0	SSP_Tiles/pass_if_in_pipe.asm
407	0	SSP_Tiles/pass_if_in_pipe.asm
408	0	SSP_Tiles/pass_if_in_pipe.asm
409	0	SSP_Tiles/turn_up-right_small.asm
40a	0	SSP_Tiles/turn_right-down_small.asm
40b	0	SSP_Tiles/top_vertical_pipe_cap_L_exit.asm
40c	0	SSP_Tiles/top_vertical_pipe_cap_R_exit.asm
40d	0	SSP_Tiles/pass_if_in_pipe.asm
40e	0	SSP_Tiles/pass_if_in_pipe.asm
40f	0	SSP_Tiles/pass_if_in_pipe.asm
410	0	SSP_Tiles/pass_if_in_pipe.asm
411	0	SSP_Tiles/pass_if_in_pipe.asm
412	0	SSP_Tiles/left_horizontal_pipe_cap_B.asm
413	0	SSP_Tiles/pass_if_in_pipe.asm
414	0	SSP_Tiles/right_horizontal_pipe_cap_B.asm
415	0	SSP_Tiles/turn_up-right.asm
416	0	SSP_Tiles/pass_if_in_pipe.asm
417	0	SSP_Tiles/pass_if_in_pipe.asm
418	0	SSP_Tiles/turn_right-down.asm
419	0	SSP_Tiles/turn_left-up_small.asm
41a	0	SSP_Tiles/turn_down-left_small.asm
41b	0	SSP_Tiles/pass_if_in_pipe.asm
41c	0	SSP_Tiles/pass_if_in_pipe.asm
41d	0	SSP_Tiles/left_horizontal_pipe_cap_B_exit.asm
41e	0	SSP_Tiles/pass_if_in_pipe.asm
41f	0	SSP_Tiles/right_horizontal_pipe_cap_B.asm
420	0	SSP_Tiles/bottom_vertical_pipe_cap_L.asm
421	0	SSP_Tiles/bottom_vertical_pipe_cap_R.asm
422	0	SSP_Tiles/left_horizontal_pipe_cap_small.asm
423	0	SSP_Tiles/pass_if_in_pipe.asm
424	0	SSP_Tiles/right_horizontal_pipe_cap_small.asm
425	0	SSP_Tiles/pass_if_in_pipe.asm
426	0	SSP_Tiles/pass_if_in_pipe.asm
427	0	SSP_Tiles/pass_if_in_pipe.asm
428	0	SSP_Tiles/pass_if_in_pipe.asm
429	0	SSP_Tiles/pass_if_in_pipe.asm
42a	0	SSP_Tiles/turn_special_small.asm
42b	0	SSP_Tiles/bottom_vertical_pipe_cap_L.asm
42c	0	SSP_Tiles/bottom_vertical_pipe_cap_R.asm
42d	0	SSP_Tiles/pass_if_in_pipe.asm
42e	0	SSP_Tiles/pass_if_in_pipe.asm
42f	0	SSP_Tiles/pass_if_in_pipe.asm
430	0	SSP_Tiles/top_vertical_pipe_cap_small_gravity.asm
431	0	SSP_Tiles/turn_special_prep_left.asm
432	0	SSP_Tiles/turn_special_prep_left.asm
433	0	SSP_Tiles/turn_special_prep_right.asm
434	0	SSP_Tiles/turn_special_prep_right.asm
435	0	SSP_Tiles/turn_left-up.asm
436	0	SSP_Tiles/pass_if_in_pipe.asm
437	0	SSP_Tiles/pass_if_in_pipe.asm
438	0	SSP_Tiles/turn_down-left.asm
439	0	SSP_Tiles/pass_if_in_pipe.asm
43a	0	SSP_Tiles/pass_if_in_pipe.asm
43b	0	SSP_Tiles/top_vertical_pipe_cap_L.asm
43c	0	SSP_Tiles/top_vertical_pipe_cap_R.asm
43d	0	SSP_Tiles/left_horizontal_pipe_cap_B.asm
43e	0	SSP_Tiles/pass_if_in_pipe.asm
43f	0	SSP_Tiles/right_horizontal_pipe_cap_B_exit.asm
440	0	SSP_Tiles/pass_if_in_pipe.asm
441	0	SSP_Tiles/turn_special_prep_up.asm
442	0	SSP_Tiles/turn_special_prep_down.asm
443	0	SSP_Tiles/turn_special_prep_left.asm
444	0	SSP_Tiles/turn_special_prep_right.asm
445	0	SSP_Tiles/top_vertical_pipe_cap_small_gravity.asm
449	0	SSP_Tiles/turn_special_L.asm
44a	0	SSP_Tiles/turn_special_R.asm
44b	0	SSP_Tiles/pass_if_in_pipe.asm
44c	0	SSP_Tiles/pass_if_in_pipe.asm
44d	0	SSP_Tiles/left_horizontal_pipe_cap_B_exit.asm
44e	0	SSP_Tiles/pass_if_in_pipe.asm
44f	0	SSP_Tiles/right_horizontal_pipe_cap_small.asm
450	0	SSP_Tiles/bottom_vertical_pipe_cap_small_gravity.asm
451	0	SSP_Tiles/turn_special_prep_up.asm
452	0	SSP_Tiles/turn_special_prep_down.asm
453	0	SSP_Tiles/turn_special_prep_up.asm
454	0	SSP_Tiles/turn_special_prep_down.asm
455	0	SSP_Tiles/pass_if_in_pipe_gravity_switch.asm
45b	0	SSP_Tiles/bottom_vertical_pipe_cap_L_exit.asm
45c	0	SSP_Tiles/bottom_vertical_pipe_cap_R_exit.asm
45d	0	SSP_Tiles/left_horizontal_pipe_cap_small.asm
45e	0	SSP_Tiles/pass_if_in_pipe.asm
45f	0	SSP_Tiles/right_horizontal_pipe_cap_B_exit.asm
460	0	SSP_Tiles/turn_special_prep_left.asm
461	0	SSP_Tiles/turn_special_prep_right.asm
462	0	SSP_Tiles/turn_special_prep_up.asm
463	0	SSP_Tiles/turn_special_prep_up.asm
465	0	SSP_Tiles/bottom_vertical_pipe_cap_small_gravity.asm
46b	0	SSP_Tiles/turn_special_prep_left.asm
46c	0	SSP_Tiles/turn_special_prep_left.asm
46d	0	SSP_Tiles/turn_special_prep_left.asm
46e	0	SSP_Tiles/top_vertical_pipe_cap_small_exit.asm
46f	0	SSP_Tiles/top_vertical_pipe_cap_small_gravity.asm
470	0	SSP_Tiles/turn_special_prep_left.asm
471	0	SSP_Tiles/turn_special_prep_right.asm
472	0	SSP_Tiles/turn_special_prep_down.asm
473	0	SSP_Tiles/turn_special_prep_down.asm
47b	0	SSP_Tiles/turn_special_prep_left.asm
47c	0	SSP_Tiles/turn_special_prep_right.asm
47d	0	SSP_Tiles/turn_special_prep_right.asm
47e	0	SSP_Tiles/pass_if_in_pipe.asm
47f	0	SSP_Tiles/pass_if_in_pipe.asm
48b	0	SSP_Tiles/turn_special_prep_right.asm
48c	0	SSP_Tiles/turn_special_prep_up.asm
48d	0	SSP_Tiles/turn_special_prep_up.asm
48e	0	SSP_Tiles/bottom_vertical_pipe_cap_small_gravity.asm
48f	0	SSP_Tiles/bottom_vertical_pipe_cap_small_exit.asm
49b	0	SSP_Tiles/turn_special_prep_right.asm
49c	0	SSP_Tiles/turn_special_prep_down.asm
49d	0	SSP_Tiles/turn_special_prep_down.asm
49e	0	SSP_Tiles/turn_special_prep_up.asm
49f	0	SSP_Tiles/turn_special_prep_down.asm
4ae	0	SSP_Tiles/turn_special_prep_up.asm
4af	0	SSP_Tiles/turn_special_prep_down.asm
